lexik_jwt_authentication:
 #   secret_key: '%env(resolve:JWT_SECRET_KEY)%'
 #  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
 #   pass_phrase: '%env(JWT_PASSPHRASE)%'
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' 
    public_key:       '%kernel.project_dir%/config/jwt/public.pem' 
    pass_phrase:      '0527394966' 
    token_ttl:        3600
    user_identity_field: email