vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_images%'
        categorie_images:
            uri_prefix: '%app.path.categorie_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.categorie_images%'   
        book_images:
            uri_prefix: '%app.path.book_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.book_images%'   
        auteur_images:
            uri_prefix: '%app.path.auteur_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.auteur_images%' 
        book_pdf:
            uri_prefix: '%app.path.book_pdf%'
            upload_destination: '%kernel.project_dir%/public%app.path.book_pdf%'             
