<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.w2yemXS' shared service.

return $this->privates['.service_locator.w2yemXS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'BookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService.php', true],
]);
