<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\routecontroller::allcomment' => ['privates', '.service_locator.v24jxCt', 'get_ServiceLocator_V24jxCtService.php', true],
    'App\\Controller\\routecontroller::authors' => ['privates', '.service_locator.sAdSnm2', 'get_ServiceLocator_SAdSnm2Service.php', true],
    'App\\Controller\\routecontroller::books' => ['privates', '.service_locator.w2yemXS', 'get_ServiceLocator_W2yemXSService.php', true],
    'App\\Controller\\routecontroller::categorie' => ['privates', '.service_locator.XetoaLa', 'get_ServiceLocator_XetoaLaService.php', true],
    'App\\Controller\\routecontroller::comment' => ['privates', '.service_locator.shLDr2s', 'get_ServiceLocator_ShLDr2sService.php', true],
    'App\\Controller\\routecontroller::edit_my_profile' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\routecontroller::filter' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'App\\Controller\\routecontroller::filter_books_from_page_aut' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'App\\Controller\\routecontroller::filter_books_from_page_cat' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'App\\Controller\\routecontroller::index' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'App\\Controller\\routecontroller::index1' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'App\\Controller\\routecontroller::inscription' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\routecontroller::like' => ['privates', '.service_locator.Kg1JKwQ', 'get_ServiceLocator_Kg1JKwQService.php', true],
    'App\\Controller\\routecontroller::onKernelResponse' => ['privates', '.service_locator.FPh_WBU', 'get_ServiceLocator_FPhWBUService.php', true],
    'App\\Controller\\routecontroller::register' => ['privates', '.service_locator.h889Fth', 'get_ServiceLocator_H889FthService.php', true],
    'kernel.listener.your_listener_name::allcomment' => ['privates', '.service_locator.v24jxCt', 'get_ServiceLocator_V24jxCtService.php', true],
    'kernel.listener.your_listener_name::authors' => ['privates', '.service_locator.sAdSnm2', 'get_ServiceLocator_SAdSnm2Service.php', true],
    'kernel.listener.your_listener_name::books' => ['privates', '.service_locator.w2yemXS', 'get_ServiceLocator_W2yemXSService.php', true],
    'kernel.listener.your_listener_name::categorie' => ['privates', '.service_locator.XetoaLa', 'get_ServiceLocator_XetoaLaService.php', true],
    'kernel.listener.your_listener_name::comment' => ['privates', '.service_locator.shLDr2s', 'get_ServiceLocator_ShLDr2sService.php', true],
    'kernel.listener.your_listener_name::edit_my_profile' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'kernel.listener.your_listener_name::filter' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'kernel.listener.your_listener_name::filter_books_from_page_aut' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'kernel.listener.your_listener_name::filter_books_from_page_cat' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'kernel.listener.your_listener_name::index' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'kernel.listener.your_listener_name::index1' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'kernel.listener.your_listener_name::inscription' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'kernel.listener.your_listener_name::like' => ['privates', '.service_locator.Kg1JKwQ', 'get_ServiceLocator_Kg1JKwQService.php', true],
    'kernel.listener.your_listener_name::onKernelResponse' => ['privates', '.service_locator.FPh_WBU', 'get_ServiceLocator_FPhWBUService.php', true],
    'kernel.listener.your_listener_name::register' => ['privates', '.service_locator.h889Fth', 'get_ServiceLocator_H889FthService.php', true],
    'App\\Controller\\routecontroller:allcomment' => ['privates', '.service_locator.v24jxCt', 'get_ServiceLocator_V24jxCtService.php', true],
    'App\\Controller\\routecontroller:authors' => ['privates', '.service_locator.sAdSnm2', 'get_ServiceLocator_SAdSnm2Service.php', true],
    'App\\Controller\\routecontroller:books' => ['privates', '.service_locator.w2yemXS', 'get_ServiceLocator_W2yemXSService.php', true],
    'App\\Controller\\routecontroller:categorie' => ['privates', '.service_locator.XetoaLa', 'get_ServiceLocator_XetoaLaService.php', true],
    'App\\Controller\\routecontroller:comment' => ['privates', '.service_locator.shLDr2s', 'get_ServiceLocator_ShLDr2sService.php', true],
    'App\\Controller\\routecontroller:edit_my_profile' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\routecontroller:filter' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'App\\Controller\\routecontroller:filter_books_from_page_aut' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'App\\Controller\\routecontroller:filter_books_from_page_cat' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'App\\Controller\\routecontroller:index' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'App\\Controller\\routecontroller:index1' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'App\\Controller\\routecontroller:inscription' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\routecontroller:like' => ['privates', '.service_locator.Kg1JKwQ', 'get_ServiceLocator_Kg1JKwQService.php', true],
    'App\\Controller\\routecontroller:onKernelResponse' => ['privates', '.service_locator.FPh_WBU', 'get_ServiceLocator_FPhWBUService.php', true],
    'App\\Controller\\routecontroller:register' => ['privates', '.service_locator.h889Fth', 'get_ServiceLocator_H889FthService.php', true],
    'kernel.listener.your_listener_name:allcomment' => ['privates', '.service_locator.v24jxCt', 'get_ServiceLocator_V24jxCtService.php', true],
    'kernel.listener.your_listener_name:authors' => ['privates', '.service_locator.sAdSnm2', 'get_ServiceLocator_SAdSnm2Service.php', true],
    'kernel.listener.your_listener_name:books' => ['privates', '.service_locator.w2yemXS', 'get_ServiceLocator_W2yemXSService.php', true],
    'kernel.listener.your_listener_name:categorie' => ['privates', '.service_locator.XetoaLa', 'get_ServiceLocator_XetoaLaService.php', true],
    'kernel.listener.your_listener_name:comment' => ['privates', '.service_locator.shLDr2s', 'get_ServiceLocator_ShLDr2sService.php', true],
    'kernel.listener.your_listener_name:edit_my_profile' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'kernel.listener.your_listener_name:filter' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'kernel.listener.your_listener_name:filter_books_from_page_aut' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'kernel.listener.your_listener_name:filter_books_from_page_cat' => ['privates', '.service_locator.sKyqCrG', 'get_ServiceLocator_SKyqCrGService.php', true],
    'kernel.listener.your_listener_name:index' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'kernel.listener.your_listener_name:index1' => ['privates', '.service_locator._Zj2bWw', 'get_ServiceLocator_Zj2bWwService.php', true],
    'kernel.listener.your_listener_name:inscription' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'kernel.listener.your_listener_name:like' => ['privates', '.service_locator.Kg1JKwQ', 'get_ServiceLocator_Kg1JKwQService.php', true],
    'kernel.listener.your_listener_name:onKernelResponse' => ['privates', '.service_locator.FPh_WBU', 'get_ServiceLocator_FPhWBUService.php', true],
    'kernel.listener.your_listener_name:register' => ['privates', '.service_locator.h889Fth', 'get_ServiceLocator_H889FthService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
