<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.FPh_WBU.Symfony\Component\HttpKernel\Event\FilterResponseEvent' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\event-dispatcher\\Event.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Event\\KernelEvent.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Event\\FilterResponseEvent.php';

return $this->privates['.errored..service_locator.FPh_WBU.Symfony\Component\HttpKernel\Event\FilterResponseEvent'] = new \Symfony\Component\HttpKernel\Event\FilterResponseEvent();
