<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\routecontroller' shared autowired service.

$this->services['App\Controller\routecontroller'] = $instance = new \App\Controller\routecontroller();

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->get_ServiceLocator_KTVqfp6Service())->withContext('App\\Controller\\routecontroller', $this));

return $instance;
