<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Kg1JKwQ' shared service.

return $this->privates['.service_locator.Kg1JKwQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'book' => ['privates', '.errored..service_locator.Kg1JKwQ.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.Kg1JKwQ": it references class "App\\Entity\\Book" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'repository' => ['privates', 'App\\Repository\\BookLikeRepository', 'getBookLikeRepositoryService.php', true],
]);
