<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCHKPxhE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCHKPxhE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCHKPxhE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCHKPxhE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCHKPxhE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CHKPxhE',
    'container.build_id' => '8257aaec',
    'container.build_time' => 1591293575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCHKPxhE');
